---
title: "(Arbeitststitel) Altersverteilung neuer Gemeinderat, Wahl am 9.6.2024"
date: 2024-06-10
draft: true
author: "Simon Lüke, Jakob Pietron"
bibliography: ../../titelei-anhang/quellen.bib
csl: ../../titelei-anhang/eva-berlin-konferenz.csl
link-citations: true
lang: de-DE
output:
  bookdown::html_document2:
    toc: true
    code_folding: hide
    number_sections: true
    mathjax: null
header-includes:
  - \renewcommand{\abstractname}{xxx}
  - \usepackage{icomma}
---

Die Wahlergebnisse sind da und...

```{r source-header, message=FALSE, echo=FALSE}

suppressWarnings(
setwd("../2024-05-30-vergleich-alter-bevoelkerung-wahllisten-gemeinderat")
# setwd gilt nur für diesen code chunk, https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html
)

source("headerGemeinderat2024.R")

```

```{r plot-vgl-neuer-rat, fig.width=10, fig.asp=0.8, message=FALSE, warning=FALSE, results='hide', fig.keep='all', fig.align = 'center', out.extra='style="display: block; margin: 40px;"', echo=FALSE}


plotDemografieUlmDistr <- demografieUlm2023Distr %>%
  mutate(Liste = paste0('Ulm\n\nn = ', length(demografieUlm2023Distr$Alter), '\nMD=', median(Alter))) %>%
  ggplot(aes(x = Alter, y = Liste)) +
  geom_density_ridges_gradient(
    bandwidth = 1.5,
    scale = 45,
    rel_min_height = 0.01,
    quantile_lines = TRUE,
    vline_color = c("#56B4E9"),
    vline_width = 1.5,
    quantile_fun = median
    ) +
  geom_vline(xintercept = 16, colour="#E69F00", linewidth = 0.8) +
  geom_vline(xintercept = demografieUlm2023Median, colour="#56B4E9", linetype = "longdash", linewidth = 0.8) +
  #scale_fill_viridis() +
  #scale_y_discrete(limits=rev, labels=rev(listenLabels$text)) +
  scale_x_continuous(limits=c(0, 100), breaks=seq(0, 90, by=5)) +
  #labs(title = 'Altersverteilung Ulmer Bevölkerung') +
  theme_ipsum() +
  theme(
    legend.position="none",
    panel.spacing = unit(0.1, "lines"),
    strip.text.x = element_text(size = 8),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    plot.margin = unit(c(0,0,0,0), 'points') #unit(c(top, right, bottom, left), units)
  )
#plotDemografieUlmDistr

plotDemografieUlmDistr <- plotDemografieUlmDistr +
  xlab("Alter") +
  theme_ipsum() +
  theme(
    legend.position="none",
    panel.spacing = unit(0.1, "lines"),
    strip.text.x = element_text(size = 8),
    axis.title.y=element_blank(),
    axis.title.x=element_text(),
    #axis.text.x = element_blank(),
    plot.margin = unit(c(0,0,0,0), 'points') #unit(c(top, right, bottom, left), units)
  )

plotDemografieUlmDistr <- plotDemografieUlmDistr +
  #theme_ipsum() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    plot.margin = unit(c(0,0,-95,0), 'points')
  )


plotRatNeu <- ratNeu %>%
  mutate(Fraktion = paste0('Gemeinderat\n2024-2029\n\nn = ', length(Alter), '\nMD=', median(Alter))) %>%
  # ',\nMedian = ', median(Alter),
  ggplot(aes(x = Alter, y = Fraktion)) + #, fill = after_stat(x))) +
  geom_density_ridges_gradient(
    scale = 45,
    rel_min_height = 0.01,
    bandwidth = 1.5,
    quantile_lines = TRUE,
    vline_color = c("#56B4E9"),
    vline_width = 1.5,
    quantile_fun = median,
    jittered_points = TRUE, #https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html
    position = position_points_jitter(width = 0.5, height = 0, seed = 42),
    point_shape = 20, #https://ggplot2.tidyverse.org/reference/aes_linetype_size_shape.html
    point_size = 2, point_alpha = .5, alpha = 0.7
    ) +
  geom_vline(xintercept = 16, colour="#E69F00", linewidth = 0.8) +
  geom_vline(xintercept = demografieUlm2023Median, colour="#56B4E9", linetype = "longdash", linewidth = 0.8) +
  #scale_fill_viridis() +
  #scale_y_discrete(limits=rev, labels=rev(listenLabels$text)) +
  scale_x_continuous(limits=c(0,100), breaks=seq(0, 90, by=5)) +
  #labs(title = 'Altersverteilung Ulmer Bevölkerung') +
  xlab("Alter") +
  theme_ipsum() +
  theme(
    legend.position="none",
    panel.spacing = unit(0.1, "lines"),
    strip.text.x = element_text(size = 8),
    axis.title.y = element_blank(),
    #axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    plot.margin = unit(c(0,0,0,0), 'points') #unit(c(top, right, bottom, left), units)
  )
#plotNeuerRat

plotRatNeu <- plotRatNeu +
  #theme_ipsum() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    plot.margin = unit(c(0,0,-20,0), 'points') #unit(c(top, right, bottom, left), units)
  )


plotAktRatMinus5 <- aktRat %>%
  mutate(Alter = Alter - 5) %>%
  mutate(Fraktion = paste0('Gemeinderat\n2019-2024\n-5 Jahre\n\nn = ', length(Alter), '\nMD = ', median(Alter))) %>%
  ggplot(aes(x = Alter, y = Fraktion)) + #, fill = after_stat(x))) +
  geom_density_ridges_gradient(
    scale = 45,
    rel_min_height = 0.01,
    bandwidth = 1.5,
    quantile_lines = TRUE,
    vline_color = c("#56B4E9"),
    vline_width = 1.5,
    quantile_fun = median,
    jittered_points = TRUE, #https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html
    position = position_points_jitter(width = 0.5, height = 0, seed = 42),
    point_shape = 20, #https://ggplot2.tidyverse.org/reference/aes_linetype_size_shape.html
    point_size = 2, point_alpha = .5, alpha = 0.7
    ) +
  geom_vline(xintercept = 16, colour="#E69F00", linewidth = 0.8) +
  geom_vline(xintercept = demografieUlm2023Median, colour="#56B4E9", linetype = "longdash", linewidth = 0.8) +
  #scale_fill_viridis() +
  #scale_y_discrete(limits=rev, labels=rev(listenLabels$text)) +
  scale_x_continuous(limits=c(0,100), breaks=seq(0, 90, by=5)) +
  #labs(title = 'Altersverteilung Ulmer Bevölkerung') +
  theme_ipsum() +
  theme(
    legend.position="none",
    panel.spacing = unit(0.1, "lines"),
    strip.text.x = element_text(size = 8),
    axis.title.y=element_blank(),
    #axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    plot.margin = unit(c(0,0,-10,0), 'points') #unit(c(top, right, bottom, left), units)
  )
#plotAktRatMinus5


plotOben <- ggarrange(
  NA, plotDemografieUlmDistr,
  labels = c(NA, NA),
  nrow = 1, ncol = 2,
  widths = c(0.00835, 1)
  )

plotUnten <- ggarrange(
  NA, plotRatNeu,
  labels = c(NA, NA),
  widths = c(0, 1),
  nrow = 1, ncol = 2
  )

plotGanzUnten <- ggarrange(
  NA, plotAktRatMinus5,
  labels = c(NA, NA),
  widths = c(0, 1),
  nrow = 1, ncol = 2
  )

suppressWarnings(
ggarrange(
  plotOben,
  plotUnten,
  plotGanzUnten,
  nrow = 3, ncol = 1,
  vjust = 0,
  heights = c(1,1,1)
  )
)

```
